### Lab 8 - Sabal Jayaswal


In [0]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from tensorflow.python.keras import models
from tensorflow.python.keras import layers
from sklearn.model_selection import train_test_split
from keras.optimizers import Adam
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

Using TensorFlow backend.


In [0]:
iris_data = load_iris() 

x = iris_data.data
y_unvectorized = iris_data.target

def vectorize(data, dimensions = 3):
    results = np.zeros((len(data),dimensions))
    for i, s in enumerate(data) :
        results[i,s]=1
    return results

y = vectorize(y_unvectorized)
y_unvectorized

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [0]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)

In [0]:
model = models.Sequential()

model.add(layers.Dense(10, input_shape=(4,), activation='relu'))
model.add(layers.Dense(10, activation='relu'))
model.add(layers.Dense(10, activation='relu'))
model.add(layers.Dense(3, activation='softmax', name='output'))

model.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(train_x, train_y, batch_size=5, epochs=20)

Epoch 1/20
24/24 [==============================] - 0s 1ms/step - loss: 1.0992 - accuracy: 0.3417
Epoch 2/20
24/24 [==============================] - 0s 1ms/step - loss: 1.0492 - accuracy: 0.3583
Epoch 3/20
24/24 [==============================] - 0s 1ms/step - loss: 1.0190 - accuracy: 0.6500
Epoch 4/20
24/24 [==============================] - 0s 1ms/step - loss: 0.9859 - accuracy: 0.6833
Epoch 5/20
24/24 [==============================] - 0s 1ms/step - loss: 0.9489 - accuracy: 0.6833
Epoch 6/20
24/24 [==============================] - 0s 1ms/step - loss: 0.9080 - accuracy: 0.6833
Epoch 7/20
24/24 [==============================] - 0s 1ms/step - loss: 0.8586 - accuracy: 0.6833
Epoch 8/20
24/24 [==============================] - 0s 1ms/step - loss: 0.8059 - accuracy: 0.6833
Epoch 9/20
24/24 [==============================] - 0s 1ms/step - loss: 0.7521 - accuracy: 0.6833
Epoch 10/20
24/24 [==============================] - 0s 1ms/step - loss: 0.6965 - accuracy: 0.6917
Epoch 11/20
24/24 [

In [0]:
results = model.evaluate(test_x, test_y)
results

1/1 [==============================] - 0s 1ms/step - loss: 0.4356 - accuracy: 0.9333


[0.43559837341308594, 0.9333333373069763]

In [0]:
#KNN
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3)
kmeans.fit(x)
y_kmeans = kmeans.predict(x)
y_pred = y_kmeans
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1], dtype=int32)

In [0]:
#Expected values
y_actual = y_unvectorized
y_actual

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [0]:
# def count(y_actual, y_pred):
#     TP = 0
#     FP = 0
#     FN = 0
#     l = len(y_pred)

#     for i in range(l):
#       for j in range(l): 
#         if [y_pred[i],y_pred[j]] == [y_actual[i],y_actual[j]]:
#            TP += 1
#     return TP

cnf_matrix = confusion_matrix(y_actual, y_pred)

TP = cnf_matrix[0][0] + cnf_matrix[1][1] + cnf_matrix[2][2] 
FP = cnf_matrix[1][0] + cnf_matrix[2][0] + cnf_matrix[2][1]
FN = cnf_matrix[0][1] + cnf_matrix[0][2] + cnf_matrix[1][2]

print("Confusion Matrix: \n", cnf_matrix, "\n")

print("TP:", TP)
print("FP:", FP)
print("FN:", FN)

precision = TP/(TP+FP)
recall = TP/(TP+FN)
f1_score = 2*precision*recall/(precision+recall)

print("Precision is:",precision)
print("Recall is:   ",recall)
print("F1 Score is: ",f1_score)

Confusion Matrix: 
 [[50  0  0]
 [ 0 48  2]
 [ 0 14 36]] 

TP: 134
FP: 14
FN: 2
Precision is: 0.9054054054054054
Recall is:    0.9852941176470589
F1 Score is:  0.943661971830986
